### PR TITLE
Add required static Fedora libraries

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by stcmz** [comment]
Does dnf not resolve dependency and install required libs automatically?

**Comment by bkmgit** [comment]
Static libraries are not installed by default:
https://unix.stackexchange.com/questions/416875/fedora-27-usr-bin-ld-cannot-find-lstdc
https://bytefreaks.net/gnulinux/bash/fedora-26-c-static-linking-cannot-find-lstdc-lm-and-lc

**Comment by stcmz** [comment]
Since these c libs are not boost libs themselves, I suggest you put them in a separate dnf line and add a comment line above it to point out the reason.

**Comment by bkmgit** [comment]
Done

**Pull request merged**
